# Generated by Django 5.1.6 on 2025-05-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='have',
            name='points',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='have',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged')], default='used', max_length=20),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='book2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_received_as_exchange', to='web.book'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='proposed', max_length=20),
        ),
        migrations.AlterField(
            model_name='saledonation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
