# Generated by Django 5.1.6 on 2025-05-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_add_status_points_to_have'),
    ]

    operations = [
    ]
