# Generated by Django 5.1.6 on 2025-05-16 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_add_status_to_have'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='book2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_received_as_exchange', to='web.book'),
        ),
    ]
