# Generated by Django 5.1.6 on 2025-05-17 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledonation',
            name='user',
        ),
        migrations.AddField(
            model_name='saledonation',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_made', to='web.user'),
        ),
        migrations.AddField(
            model_name='saledonation',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_made', to='web.user'),
        ),
    ]
