# Generated by Django 5.1.6 on 2025-04-06 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_user_auth_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tengo',
            new_name='Have',
        ),
        migrations.RenameModel(
            old_name='Quiero',
            new_name='Want',
        ),
        migrations.RemoveField(
            model_name='vendadonacio',
            name='book',
        ),
        migrations.RemoveField(
            model_name='vendadonacio',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ubication',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='want',
            old_name='prioritat',
            new_name='priority',
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='proposed', max_length=20)),
                ('book1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_exchanged_by', to='web.book')),
                ('book2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_received_as_exchange', to='web.book')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_made', to='web.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_received', to='web.user')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Intercanvi',
        ),
        migrations.DeleteModel(
            name='VendaDonacio',
        ),
    ]
